CC=g++

all: Cycle_Games

Cycle_Games: Source.cpp
	$(CC) --std=c++17 Source.cpp -o Cycle_Games

clean:
CC=g++

all: Cycle_Games

Cycle_Games: Source.cpp
	$(CC) --std=c++17 Source.cpp -o Cycle_Games

clean:
	rm Cycle_Games